<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile


?>
<?php
$_productCollection = $block->getTaggedCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */
			echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="tag list">
		<?php $tags = $block->getAllTags(); ?>
		<?php foreach($tags as $tag): ?>
			<a class="btn action primary" href="<?=$block->getFrontendUrl().'/'.$tag->getTag();?>"><?=$tag->getTag();?> (<?=$tag->getAmount();?>)</a>
		<?php endforeach; ?>
	</div>
    <div class="toolbar-top">
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
	</div>
	<?php echo $block->getAdditionalHtml() ?>
	<?php
	if ($block->getMode() == 'grid') {
		$viewMode        = 'grid';
		$image           = 'category_page_grid';
		$showDescription = false;
		$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else {
		$viewMode        = 'list';
		$image           = 'category_page_list';
		$showDescription = true;
		$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */
		echo $viewMode; ?> products-<?php /* @escapeNotVerified */
		echo $viewMode; ?>">
		<ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
					<div class="product-item-info" data-container="product-grid">
						<div class="item-inner">
							<div class="box-image">
								<?php $productImage = $block->getImage($_product, $image); ?>
								<a href="<?php /* @escapeNotVerified */
								echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
							</div>
							
							<div class="product details product-item-details box-info">
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

								<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
                                <h2 class="product name product-item-name product-name">
									<a class="product-item-link" href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */
										echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h2>
							</div>
						</div>
					</div>
                </li>
			<?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
	</div>
<?php endif; ?>
