<div class="col-xs-12">
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$limit = $block->getProductLimit();

if ($exist = count($block->getTaggedProducts($limit))) {
	$type  = 'upsell';
	$class = $type;

	$image       = 'upsell_products_list';
	$hover_image = 'category_page_grid-hover';
	$title       = __('Tagged products');
	$items       = $block->getTaggedProducts($limit);
	
	$shuffle     = 0;
	$showAddTo         = true;
	$showCart          = false;
	$templateType      = null;
	$description       = false;
	$canItemsAddToCart = true;
}


?>
<?php if ($exist): ?>


    <div class="related-upsell-wrapper block block-detail <?php /* @escapeNotVerified */
	echo $class; ?>">
    <div class="detail-title">
        <span id="block-<?php /* @escapeNotVerified */
		echo $class ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */
			echo $title; ?></span>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */
	echo $class ?>-heading">
        <div class="grid products-grid products-<?php /* @escapeNotVerified */
		echo $type; ?>">
            <div class="grid-product-type products list items product-items slider-products">
                <?php foreach ($items as $_item):  ?>
                    <div class="item product product-item">
					<div class="item-inner">
						<div class="product-item-info">
							<div class="box-image">
								<a href="<?php /* @escapeNotVerified */
								echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
							</div>
							
							<div class="product details product-item-details box-info">
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>

                                <h2 class="product name product-item-name product-name">
									<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */
									echo $block->getProductUrl($_item) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</h2>

								<?php /* @escapeNotVerified */
								echo $block->getProductPrice($_item); ?>

                                <div class="bottom-action">
									<?php if ($_item->isSaleable()): ?>
										<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
											<button class="action tocart btn-action btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */
											echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */
											echo __('Add to Cart') ?>">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Cart') ?></span>
											</button>
										<?php else: ?>
											<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
											$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
											?>
											<button class="action tocart btn-action btn-cart" data-post='<?php /* @escapeNotVerified */
											echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */
											echo __('Add to Cart') ?>">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Cart') ?></span>
											</button>
										<?php endif; ?>
									<?php else: ?>
										<?php if ($_item->getIsSalable()): ?>
											<div class="stock available"><span><?php /* @escapeNotVerified */
													echo __('In stock') ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php /* @escapeNotVerified */
													echo __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
							</div>
							
							
						</div>
					</div>
                </div>
				<?php endforeach ?>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
	require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        jQuery(".<?php echo $type;?> .slider-products").owlCarousel({

            responsive: {
                0: {
                    items: 1
                },
                480: {
                    items: 2
                },
                768: {
                    items: 3
                },
                992: {
                    items: 4
                },
                1200: {
                    items: 5
                }
            },

            autoplay: false,
            loop: false,
            nav: true, // Show next and prev buttons
            dots: false,
            autoplaySpeed: 500,
            navSpeed: 500,
            dotsSpeed: 500,
            autoplayHoverPause: true,
            margin: 30,

        });
    });	
</script>
<?php endif; ?>
</div>
