<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile


?>
<?php
$_productCollection = $block->getTaggedCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="tag list">
        <?php $tags = $block->getAllTags(); ?>
        <?php foreach($tags as $tag): ?>
            <a class="btn action primary" href="<?=$block->getTagsFrontendUrl().'/'.$tag->getTag();?>"><?=$tag->getTag();?> (<?=$tag->getAmount();?>)</a>
        <?php endforeach; ?>
    </div>
    <div class="toolbar-top">
    <?php if ($block->getCustomPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getCustomPagerHtml(); ?></div>
    <?php endif ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php

        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */
        echo $viewMode; ?> products-<?php /* @escapeNotVerified */
        echo $viewMode; ?>">
        <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <div class="item-inner">
                            <div class="box-image">
                                <?php $productImage = $block->getImage($_product, $image); ?>
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                            </div>
                            
                            <div class="product details product-item-details box-info">
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h2 class="product name product-item-name product-name">
                                    <a class="product-item-link" href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h2>
                                <?php /* @escapeNotVerified */
                                echo $block->getProductPrice($_product); ?>

                                <div class="bottom-action">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <button class="action tocart btn-action btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */
                                            echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php /* @escapeNotVerified */
                                            echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                            ?>
                                            <button class="action tocart btn-action btn-cart" data-post='<?php /* @escapeNotVerified */
                                            echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */
                                            echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
    <?php if ($block->getCustomPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getCustomPagerHtml(); ?></div>
    <?php endif ?>
    </div>
<?php endif; ?>
